
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 23 00:28:22 CST 2019
//----------------------------------------------------

package Parser.HTML;

/** CUP generated class containing symbol constants. */
public class symHTML {
  /* terminals */
  public static final int CSUB = 65;
  public static final int AQUA = 42;
  public static final int LEFT = 43;
  public static final int HEXADECIMAL = 78;
  public static final int OTITLE = 93;
  public static final int GT = 82;
  public static final int AMP = 83;
  public static final int AACUTE = 84;
  public static final int TYPE = 97;
  public static final int UACUTE = 88;
  public static final int TEAL = 29;
  public static final int BGCOLOR = 19;
  public static final int RIGHT = 44;
  public static final int CIRCLE = 47;
  public static final int CBODY = 99;
  public static final int CBLOCKQUOTE = 72;
  public static final int OACUTE = 87;
  public static final int DIAGONAL = 8;
  public static final int NAME = 73;
  public static final int OSUBRA = 56;
  public static final int OCENTER = 52;
  public static final int TEXTO = 79;
  public static final int MAROON = 32;
  public static final int SQUARE = 48;
  public static final int BLUE = 31;
  public static final int YELLOW = 41;
  public static final int CHEAD = 5;
  public static final int NTILDEMAY = 89;
  public static final int IACUTE = 86;
  public static final int FUCHSIA = 36;
  public static final int WHITE = 38;
  public static final int LT = 81;
  public static final int NUMERO = 74;
  public static final int BLACK = 27;
  public static final int CCERRADO = 26;
  public static final int OSUP = 66;
  public static final int FONT = 20;
  public static final int CTITLE = 94;
  public static final int GRAY = 34;
  public static final int LI = 14;
  public static final int CENTER = 45;
  public static final int CCENTER = 53;
  public static final int APERTURA = 6;
  public static final int TEXT = 16;
  public static final int OSUB = 64;
  public static final int CIERRE = 7;
  public static final int PURPLE = 39;
  public static final int WIDTH = 18;
  public static final int CABIERTO = 95;
  public static final int CSUBRA = 57;
  public static final int OSTRIKE = 60;
  public static final int TAG = 80;
  public static final int OHTML = 2;
  public static final int IGUAL = 25;
  public static final int OLIVE = 28;
  public static final int OBLINK = 62;
  public static final int PORCENTAJE = 75;
  public static final int PAR = 102;
  public static final int TIPO = 77;
  public static final int ALIGN = 17;
  public static final int ONOBR = 69;
  public static final int CSTRIKE = 61;
  public static final int FACE = 11;
  public static final int SIGNO_GATO = 92;
  public static final int NAVY = 33;
  public static final int OITALIC = 58;
  public static final int CREF = 51;
  public static final int CFONT = 24;
  public static final int LINK = 96;
  public static final int EOF = 0;
  public static final int OBOLD = 54;
  public static final int DISC = 49;
  public static final int COL = 100;
  public static final int EACUTE = 85;
  public static final int PARAGRAPH = 15;
  public static final int CUL = 101;
  public static final int CP = 23;
  public static final int CHTML = 3;
  public static final int CBLINK = 63;
  public static final int BODY = 9;
  public static final int HREF = 22;
  public static final int COMILLA = 76;
  public static final int error = 1;
  public static final int CITALIC = 59;
  public static final int START = 91;
  public static final int OL = 13;
  public static final int CNOBR = 70;
  public static final int COLOR = 98;
  public static final int UL = 12;
  public static final int SILVER = 40;
  public static final int LIME = 35;
  public static final int JUSTIFIED = 46;
  public static final int OBLOCKQUOTE = 71;
  public static final int BR = 68;
  public static final int RED = 30;
  public static final int HR = 21;
  public static final int SIZE = 10;
  public static final int OHEAD = 4;
  public static final int OREF = 50;
  public static final int CBOLD = 55;
  public static final int CSUP = 67;
  public static final int NTILDEMIN = 90;
  public static final int GREEN = 37;
}

