
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 24 00:21:22 CST 2019
//----------------------------------------------------

package Parser.EmbedCode;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 7;
  public static final int DOSPUNTOS = 5;
  public static final int CABIERTO = 36;
  public static final int PABIERTO = 33;
  public static final int PUNTOYCOMA = 19;
  public static final int DIFERENTE = 23;
  public static final int INTEGER = 9;
  public static final int FIN = 3;
  public static final int FOR = 28;
  public static final int IDENTIFICADOR = 6;
  public static final int MENORIGUAL = 20;
  public static final int IGUAL = 22;
  public static final int DIV = 15;
  public static final int BEGIN = 30;
  public static final int MUX = 14;
  public static final int IF = 24;
  public static final int MAYORIGUAL = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOS = 13;
  public static final int MENOR = 16;
  public static final int MAYOR = 17;
  public static final int CCERRADO = 37;
  public static final int PCERRADO = 34;
  public static final int ELSE = 26;
  public static final int TO = 29;
  public static final int WHILE = 27;
  public static final int THEN = 25;
  public static final int END = 31;
  public static final int STRING = 11;
  public static final int INICIO = 2;
  public static final int DEFINICION = 8;
  public static final int TEXTO = 18;
  public static final int VAR = 4;
  public static final int PRINT = 32;
  public static final int MAS = 12;
}

